# Generated by Django 4.2.7 on 2024-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='split_share',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenseparticipants',
            name='expense_type',
            field=models.CharField(choices=[('EQUAL', 'EQUAL'), ('EXACT', 'EXACT'), ('PERCENT', 'PERCENT')], max_length=10),
        ),
    ]
