# Generated by Django 4.2.7 on 2024-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_split_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
